version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=apimok
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    command: python main.py 0.0.0.0:5000
    volumes:
      - .:/mok_api_project
    ports:
      - '5000:5000'
    depends_on:
      - db
